fragment HistoriasParts on Historias {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  spotifyUrl
  temporada
  capitulo
  body
}

fragment ConflictosParts on Conflictos {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  spotifyUrl
  temporada
  capitulo
  body
}

fragment SerendipiaParts on Serendipia {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  spotifyUrl
  temporada
  capitulo
  body
}

fragment AnalisisParts on Analisis {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  spotifyUrl
  temporada
  capitulo
  body
}

fragment MarcoParts on Marco {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  spotifyUrl
  temporada
  capitulo
  body
}

fragment PodcastParts on Podcast {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  spotifyUrl
  temporada
  capitulo
  body
}
