//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  historias: Historias;
  historiasConnection: HistoriasConnection;
  conflictos: Conflictos;
  conflictosConnection: ConflictosConnection;
  serendipia: Serendipia;
  serendipiaConnection: SerendipiaConnection;
  analisis: Analisis;
  analisisConnection: AnalisisConnection;
  marco: Marco;
  marcoConnection: MarcoConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHistoriasArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHistoriasConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HistoriasFilter>;
};


export type QueryConflictosArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryConflictosConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConflictosFilter>;
};


export type QuerySerendipiaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySerendipiaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SerendipiaFilter>;
};


export type QueryAnalisisArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAnalisisConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AnalisisFilter>;
};


export type QueryMarcoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryMarcoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MarcoFilter>;
};

export type DocumentFilter = {
  historias?: InputMaybe<HistoriasFilter>;
  conflictos?: InputMaybe<ConflictosFilter>;
  serendipia?: InputMaybe<SerendipiaFilter>;
  analisis?: InputMaybe<AnalisisFilter>;
  marco?: InputMaybe<MarcoFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Historias | Conflictos | Serendipia | Analisis | Marco | Folder;

export type Historias = Node & Document & {
  __typename?: 'Historias';
  titulo: Scalars['String']['output'];
  seccion: Scalars['String']['output'];
  industria: Scalars['String']['output'];
  mecanismo?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tema: Scalars['String']['output'];
  fecha: Scalars['String']['output'];
  resumen: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type HistoriasFilter = {
  titulo?: InputMaybe<StringFilter>;
  seccion?: InputMaybe<StringFilter>;
  industria?: InputMaybe<StringFilter>;
  mecanismo?: InputMaybe<StringFilter>;
  tema?: InputMaybe<StringFilter>;
  fecha?: InputMaybe<DatetimeFilter>;
  resumen?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type HistoriasConnectionEdges = {
  __typename?: 'HistoriasConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Historias>;
};

export type HistoriasConnection = Connection & {
  __typename?: 'HistoriasConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HistoriasConnectionEdges>>>;
};

export type Conflictos = Node & Document & {
  __typename?: 'Conflictos';
  titulo: Scalars['String']['output'];
  seccion: Scalars['String']['output'];
  industria: Scalars['String']['output'];
  mecanismo?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tema: Scalars['String']['output'];
  fecha: Scalars['String']['output'];
  resumen: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ConflictosFilter = {
  titulo?: InputMaybe<StringFilter>;
  seccion?: InputMaybe<StringFilter>;
  industria?: InputMaybe<StringFilter>;
  mecanismo?: InputMaybe<StringFilter>;
  tema?: InputMaybe<StringFilter>;
  fecha?: InputMaybe<DatetimeFilter>;
  resumen?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type ConflictosConnectionEdges = {
  __typename?: 'ConflictosConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Conflictos>;
};

export type ConflictosConnection = Connection & {
  __typename?: 'ConflictosConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ConflictosConnectionEdges>>>;
};

export type Serendipia = Node & Document & {
  __typename?: 'Serendipia';
  titulo: Scalars['String']['output'];
  seccion: Scalars['String']['output'];
  industria: Scalars['String']['output'];
  mecanismo?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tema: Scalars['String']['output'];
  fecha: Scalars['String']['output'];
  resumen: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SerendipiaFilter = {
  titulo?: InputMaybe<StringFilter>;
  seccion?: InputMaybe<StringFilter>;
  industria?: InputMaybe<StringFilter>;
  mecanismo?: InputMaybe<StringFilter>;
  tema?: InputMaybe<StringFilter>;
  fecha?: InputMaybe<DatetimeFilter>;
  resumen?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type SerendipiaConnectionEdges = {
  __typename?: 'SerendipiaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Serendipia>;
};

export type SerendipiaConnection = Connection & {
  __typename?: 'SerendipiaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SerendipiaConnectionEdges>>>;
};

export type Analisis = Node & Document & {
  __typename?: 'Analisis';
  titulo: Scalars['String']['output'];
  seccion: Scalars['String']['output'];
  industria: Scalars['String']['output'];
  mecanismo?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tema: Scalars['String']['output'];
  fecha: Scalars['String']['output'];
  resumen: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AnalisisFilter = {
  titulo?: InputMaybe<StringFilter>;
  seccion?: InputMaybe<StringFilter>;
  industria?: InputMaybe<StringFilter>;
  mecanismo?: InputMaybe<StringFilter>;
  tema?: InputMaybe<StringFilter>;
  fecha?: InputMaybe<DatetimeFilter>;
  resumen?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type AnalisisConnectionEdges = {
  __typename?: 'AnalisisConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Analisis>;
};

export type AnalisisConnection = Connection & {
  __typename?: 'AnalisisConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AnalisisConnectionEdges>>>;
};

export type Marco = Node & Document & {
  __typename?: 'Marco';
  titulo: Scalars['String']['output'];
  seccion: Scalars['String']['output'];
  industria: Scalars['String']['output'];
  mecanismo?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  tema: Scalars['String']['output'];
  fecha: Scalars['String']['output'];
  resumen: Scalars['String']['output'];
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type MarcoFilter = {
  titulo?: InputMaybe<StringFilter>;
  seccion?: InputMaybe<StringFilter>;
  industria?: InputMaybe<StringFilter>;
  mecanismo?: InputMaybe<StringFilter>;
  tema?: InputMaybe<StringFilter>;
  fecha?: InputMaybe<DatetimeFilter>;
  resumen?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type MarcoConnectionEdges = {
  __typename?: 'MarcoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Marco>;
};

export type MarcoConnection = Connection & {
  __typename?: 'MarcoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<MarcoConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateHistorias: Historias;
  createHistorias: Historias;
  updateConflictos: Conflictos;
  createConflictos: Conflictos;
  updateSerendipia: Serendipia;
  createSerendipia: Serendipia;
  updateAnalisis: Analisis;
  createAnalisis: Analisis;
  updateMarco: Marco;
  createMarco: Marco;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateHistoriasArgs = {
  relativePath: Scalars['String']['input'];
  params: HistoriasMutation;
};


export type MutationCreateHistoriasArgs = {
  relativePath: Scalars['String']['input'];
  params: HistoriasMutation;
};


export type MutationUpdateConflictosArgs = {
  relativePath: Scalars['String']['input'];
  params: ConflictosMutation;
};


export type MutationCreateConflictosArgs = {
  relativePath: Scalars['String']['input'];
  params: ConflictosMutation;
};


export type MutationUpdateSerendipiaArgs = {
  relativePath: Scalars['String']['input'];
  params: SerendipiaMutation;
};


export type MutationCreateSerendipiaArgs = {
  relativePath: Scalars['String']['input'];
  params: SerendipiaMutation;
};


export type MutationUpdateAnalisisArgs = {
  relativePath: Scalars['String']['input'];
  params: AnalisisMutation;
};


export type MutationCreateAnalisisArgs = {
  relativePath: Scalars['String']['input'];
  params: AnalisisMutation;
};


export type MutationUpdateMarcoArgs = {
  relativePath: Scalars['String']['input'];
  params: MarcoMutation;
};


export type MutationCreateMarcoArgs = {
  relativePath: Scalars['String']['input'];
  params: MarcoMutation;
};

export type DocumentUpdateMutation = {
  historias?: InputMaybe<HistoriasMutation>;
  conflictos?: InputMaybe<ConflictosMutation>;
  serendipia?: InputMaybe<SerendipiaMutation>;
  analisis?: InputMaybe<AnalisisMutation>;
  marco?: InputMaybe<MarcoMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  historias?: InputMaybe<HistoriasMutation>;
  conflictos?: InputMaybe<ConflictosMutation>;
  serendipia?: InputMaybe<SerendipiaMutation>;
  analisis?: InputMaybe<AnalisisMutation>;
  marco?: InputMaybe<MarcoMutation>;
};

export type HistoriasMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  seccion?: InputMaybe<Scalars['String']['input']>;
  industria?: InputMaybe<Scalars['String']['input']>;
  mecanismo?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tema?: InputMaybe<Scalars['String']['input']>;
  fecha?: InputMaybe<Scalars['String']['input']>;
  resumen?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type ConflictosMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  seccion?: InputMaybe<Scalars['String']['input']>;
  industria?: InputMaybe<Scalars['String']['input']>;
  mecanismo?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tema?: InputMaybe<Scalars['String']['input']>;
  fecha?: InputMaybe<Scalars['String']['input']>;
  resumen?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type SerendipiaMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  seccion?: InputMaybe<Scalars['String']['input']>;
  industria?: InputMaybe<Scalars['String']['input']>;
  mecanismo?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tema?: InputMaybe<Scalars['String']['input']>;
  fecha?: InputMaybe<Scalars['String']['input']>;
  resumen?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type AnalisisMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  seccion?: InputMaybe<Scalars['String']['input']>;
  industria?: InputMaybe<Scalars['String']['input']>;
  mecanismo?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tema?: InputMaybe<Scalars['String']['input']>;
  fecha?: InputMaybe<Scalars['String']['input']>;
  resumen?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type MarcoMutation = {
  titulo?: InputMaybe<Scalars['String']['input']>;
  seccion?: InputMaybe<Scalars['String']['input']>;
  industria?: InputMaybe<Scalars['String']['input']>;
  mecanismo?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  tema?: InputMaybe<Scalars['String']['input']>;
  fecha?: InputMaybe<Scalars['String']['input']>;
  resumen?: InputMaybe<Scalars['String']['input']>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type HistoriasPartsFragment = { __typename: 'Historias', titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null };

export type ConflictosPartsFragment = { __typename: 'Conflictos', titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null };

export type SerendipiaPartsFragment = { __typename: 'Serendipia', titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null };

export type AnalisisPartsFragment = { __typename: 'Analisis', titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null };

export type MarcoPartsFragment = { __typename: 'Marco', titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null };

export type HistoriasQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HistoriasQuery = { __typename?: 'Query', historias: { __typename: 'Historias', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type HistoriasConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HistoriasFilter>;
}>;


export type HistoriasConnectionQuery = { __typename?: 'Query', historiasConnection: { __typename?: 'HistoriasConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HistoriasConnectionEdges', cursor: string, node?: { __typename: 'Historias', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type ConflictosQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ConflictosQuery = { __typename?: 'Query', conflictos: { __typename: 'Conflictos', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ConflictosConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ConflictosFilter>;
}>;


export type ConflictosConnectionQuery = { __typename?: 'Query', conflictosConnection: { __typename?: 'ConflictosConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ConflictosConnectionEdges', cursor: string, node?: { __typename: 'Conflictos', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SerendipiaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SerendipiaQuery = { __typename?: 'Query', serendipia: { __typename: 'Serendipia', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type SerendipiaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SerendipiaFilter>;
}>;


export type SerendipiaConnectionQuery = { __typename?: 'Query', serendipiaConnection: { __typename?: 'SerendipiaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SerendipiaConnectionEdges', cursor: string, node?: { __typename: 'Serendipia', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type AnalisisQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AnalisisQuery = { __typename?: 'Query', analisis: { __typename: 'Analisis', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type AnalisisConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AnalisisFilter>;
}>;


export type AnalisisConnectionQuery = { __typename?: 'Query', analisisConnection: { __typename?: 'AnalisisConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AnalisisConnectionEdges', cursor: string, node?: { __typename: 'Analisis', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type MarcoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type MarcoQuery = { __typename?: 'Query', marco: { __typename: 'Marco', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type MarcoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<MarcoFilter>;
}>;


export type MarcoConnectionQuery = { __typename?: 'Query', marcoConnection: { __typename?: 'MarcoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'MarcoConnectionEdges', cursor: string, node?: { __typename: 'Marco', id: string, titulo: string, seccion: string, industria: string, mecanismo?: Array<string | null> | null, tema: string, fecha: string, resumen: string, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const HistoriasPartsFragmentDoc = gql`
    fragment HistoriasParts on Historias {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  body
}
    `;
export const ConflictosPartsFragmentDoc = gql`
    fragment ConflictosParts on Conflictos {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  body
}
    `;
export const SerendipiaPartsFragmentDoc = gql`
    fragment SerendipiaParts on Serendipia {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  body
}
    `;
export const AnalisisPartsFragmentDoc = gql`
    fragment AnalisisParts on Analisis {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  body
}
    `;
export const MarcoPartsFragmentDoc = gql`
    fragment MarcoParts on Marco {
  __typename
  titulo
  seccion
  industria
  mecanismo
  tema
  fecha
  resumen
  body
}
    `;
export const HistoriasDocument = gql`
    query historias($relativePath: String!) {
  historias(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HistoriasParts
  }
}
    ${HistoriasPartsFragmentDoc}`;
export const HistoriasConnectionDocument = gql`
    query historiasConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HistoriasFilter) {
  historiasConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HistoriasParts
      }
    }
  }
}
    ${HistoriasPartsFragmentDoc}`;
export const ConflictosDocument = gql`
    query conflictos($relativePath: String!) {
  conflictos(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ConflictosParts
  }
}
    ${ConflictosPartsFragmentDoc}`;
export const ConflictosConnectionDocument = gql`
    query conflictosConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ConflictosFilter) {
  conflictosConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ConflictosParts
      }
    }
  }
}
    ${ConflictosPartsFragmentDoc}`;
export const SerendipiaDocument = gql`
    query serendipia($relativePath: String!) {
  serendipia(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SerendipiaParts
  }
}
    ${SerendipiaPartsFragmentDoc}`;
export const SerendipiaConnectionDocument = gql`
    query serendipiaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SerendipiaFilter) {
  serendipiaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SerendipiaParts
      }
    }
  }
}
    ${SerendipiaPartsFragmentDoc}`;
export const AnalisisDocument = gql`
    query analisis($relativePath: String!) {
  analisis(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AnalisisParts
  }
}
    ${AnalisisPartsFragmentDoc}`;
export const AnalisisConnectionDocument = gql`
    query analisisConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AnalisisFilter) {
  analisisConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AnalisisParts
      }
    }
  }
}
    ${AnalisisPartsFragmentDoc}`;
export const MarcoDocument = gql`
    query marco($relativePath: String!) {
  marco(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...MarcoParts
  }
}
    ${MarcoPartsFragmentDoc}`;
export const MarcoConnectionDocument = gql`
    query marcoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: MarcoFilter) {
  marcoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...MarcoParts
      }
    }
  }
}
    ${MarcoPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      historias(variables: HistoriasQueryVariables, options?: C): Promise<{data: HistoriasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HistoriasQueryVariables, query: string}> {
        return requester<{data: HistoriasQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HistoriasQueryVariables, query: string}, HistoriasQueryVariables>(HistoriasDocument, variables, options);
      },
    historiasConnection(variables?: HistoriasConnectionQueryVariables, options?: C): Promise<{data: HistoriasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HistoriasConnectionQueryVariables, query: string}> {
        return requester<{data: HistoriasConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HistoriasConnectionQueryVariables, query: string}, HistoriasConnectionQueryVariables>(HistoriasConnectionDocument, variables, options);
      },
    conflictos(variables: ConflictosQueryVariables, options?: C): Promise<{data: ConflictosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConflictosQueryVariables, query: string}> {
        return requester<{data: ConflictosQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConflictosQueryVariables, query: string}, ConflictosQueryVariables>(ConflictosDocument, variables, options);
      },
    conflictosConnection(variables?: ConflictosConnectionQueryVariables, options?: C): Promise<{data: ConflictosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConflictosConnectionQueryVariables, query: string}> {
        return requester<{data: ConflictosConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ConflictosConnectionQueryVariables, query: string}, ConflictosConnectionQueryVariables>(ConflictosConnectionDocument, variables, options);
      },
    serendipia(variables: SerendipiaQueryVariables, options?: C): Promise<{data: SerendipiaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SerendipiaQueryVariables, query: string}> {
        return requester<{data: SerendipiaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SerendipiaQueryVariables, query: string}, SerendipiaQueryVariables>(SerendipiaDocument, variables, options);
      },
    serendipiaConnection(variables?: SerendipiaConnectionQueryVariables, options?: C): Promise<{data: SerendipiaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SerendipiaConnectionQueryVariables, query: string}> {
        return requester<{data: SerendipiaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SerendipiaConnectionQueryVariables, query: string}, SerendipiaConnectionQueryVariables>(SerendipiaConnectionDocument, variables, options);
      },
    analisis(variables: AnalisisQueryVariables, options?: C): Promise<{data: AnalisisQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnalisisQueryVariables, query: string}> {
        return requester<{data: AnalisisQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnalisisQueryVariables, query: string}, AnalisisQueryVariables>(AnalisisDocument, variables, options);
      },
    analisisConnection(variables?: AnalisisConnectionQueryVariables, options?: C): Promise<{data: AnalisisConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnalisisConnectionQueryVariables, query: string}> {
        return requester<{data: AnalisisConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AnalisisConnectionQueryVariables, query: string}, AnalisisConnectionQueryVariables>(AnalisisConnectionDocument, variables, options);
      },
    marco(variables: MarcoQueryVariables, options?: C): Promise<{data: MarcoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MarcoQueryVariables, query: string}> {
        return requester<{data: MarcoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MarcoQueryVariables, query: string}, MarcoQueryVariables>(MarcoDocument, variables, options);
      },
    marcoConnection(variables?: MarcoConnectionQueryVariables, options?: C): Promise<{data: MarcoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MarcoConnectionQueryVariables, query: string}> {
        return requester<{data: MarcoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: MarcoConnectionQueryVariables, query: string}, MarcoConnectionQueryVariables>(MarcoConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  