//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  topic: Topic;
  topicConnection: TopicConnection;
  piece: Piece;
  pieceConnection: PieceConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTopicArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTopicConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TopicFilter>;
};


export type QueryPieceArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPieceConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PieceFilter>;
};

export type DocumentFilter = {
  topic?: InputMaybe<TopicFilter>;
  piece?: InputMaybe<PieceFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Topic | Piece | Folder;

export type Topic = Node & Document & {
  __typename?: 'Topic';
  name: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  related_topic_ids?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TopicFilter = {
  name?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  related_topic_ids?: InputMaybe<StringFilter>;
};

export type TopicConnectionEdges = {
  __typename?: 'TopicConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Topic>;
};

export type TopicConnection = Connection & {
  __typename?: 'TopicConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TopicConnectionEdges>>>;
};

export type Piece = Node & Document & {
  __typename?: 'Piece';
  title: Scalars['String']['output'];
  topic_id: Scalars['String']['output'];
  format: Scalars['String']['output'];
  summary?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  body?: Maybe<Scalars['JSON']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type RichTextFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type PieceFilter = {
  title?: InputMaybe<StringFilter>;
  topic_id?: InputMaybe<StringFilter>;
  format?: InputMaybe<StringFilter>;
  summary?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
  body?: InputMaybe<RichTextFilter>;
};

export type PieceConnectionEdges = {
  __typename?: 'PieceConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Piece>;
};

export type PieceConnection = Connection & {
  __typename?: 'PieceConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PieceConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateTopic: Topic;
  createTopic: Topic;
  updatePiece: Piece;
  createPiece: Piece;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateTopicArgs = {
  relativePath: Scalars['String']['input'];
  params: TopicMutation;
};


export type MutationCreateTopicArgs = {
  relativePath: Scalars['String']['input'];
  params: TopicMutation;
};


export type MutationUpdatePieceArgs = {
  relativePath: Scalars['String']['input'];
  params: PieceMutation;
};


export type MutationCreatePieceArgs = {
  relativePath: Scalars['String']['input'];
  params: PieceMutation;
};

export type DocumentUpdateMutation = {
  topic?: InputMaybe<TopicMutation>;
  piece?: InputMaybe<PieceMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  topic?: InputMaybe<TopicMutation>;
  piece?: InputMaybe<PieceMutation>;
};

export type TopicMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  related_topic_ids?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type PieceMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  topic_id?: InputMaybe<Scalars['String']['input']>;
  format?: InputMaybe<Scalars['String']['input']>;
  summary?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  body?: InputMaybe<Scalars['JSON']['input']>;
};

export type TopicPartsFragment = { __typename: 'Topic', name: string, description?: string | null, related_topic_ids?: Array<string | null> | null };

export type PiecePartsFragment = { __typename: 'Piece', title: string, topic_id: string, format: string, summary?: string | null, tags?: Array<string | null> | null, body?: any | null };

export type TopicQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TopicQuery = { __typename?: 'Query', topic: { __typename: 'Topic', id: string, name: string, description?: string | null, related_topic_ids?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TopicConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TopicFilter>;
}>;


export type TopicConnectionQuery = { __typename?: 'Query', topicConnection: { __typename?: 'TopicConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TopicConnectionEdges', cursor: string, node?: { __typename: 'Topic', id: string, name: string, description?: string | null, related_topic_ids?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type PieceQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PieceQuery = { __typename?: 'Query', piece: { __typename: 'Piece', id: string, title: string, topic_id: string, format: string, summary?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PieceConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PieceFilter>;
}>;


export type PieceConnectionQuery = { __typename?: 'Query', pieceConnection: { __typename?: 'PieceConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PieceConnectionEdges', cursor: string, node?: { __typename: 'Piece', id: string, title: string, topic_id: string, format: string, summary?: string | null, tags?: Array<string | null> | null, body?: any | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const TopicPartsFragmentDoc = gql`
    fragment TopicParts on Topic {
  __typename
  name
  description
  related_topic_ids
}
    `;
export const PiecePartsFragmentDoc = gql`
    fragment PieceParts on Piece {
  __typename
  title
  topic_id
  format
  summary
  tags
  body
}
    `;
export const TopicDocument = gql`
    query topic($relativePath: String!) {
  topic(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TopicParts
  }
}
    ${TopicPartsFragmentDoc}`;
export const TopicConnectionDocument = gql`
    query topicConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TopicFilter) {
  topicConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TopicParts
      }
    }
  }
}
    ${TopicPartsFragmentDoc}`;
export const PieceDocument = gql`
    query piece($relativePath: String!) {
  piece(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PieceParts
  }
}
    ${PiecePartsFragmentDoc}`;
export const PieceConnectionDocument = gql`
    query pieceConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PieceFilter) {
  pieceConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PieceParts
      }
    }
  }
}
    ${PiecePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      topic(variables: TopicQueryVariables, options?: C): Promise<{data: TopicQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicQueryVariables, query: string}> {
        return requester<{data: TopicQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicQueryVariables, query: string}, TopicQueryVariables>(TopicDocument, variables, options);
      },
    topicConnection(variables?: TopicConnectionQueryVariables, options?: C): Promise<{data: TopicConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicConnectionQueryVariables, query: string}> {
        return requester<{data: TopicConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TopicConnectionQueryVariables, query: string}, TopicConnectionQueryVariables>(TopicConnectionDocument, variables, options);
      },
    piece(variables: PieceQueryVariables, options?: C): Promise<{data: PieceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PieceQueryVariables, query: string}> {
        return requester<{data: PieceQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PieceQueryVariables, query: string}, PieceQueryVariables>(PieceDocument, variables, options);
      },
    pieceConnection(variables?: PieceConnectionQueryVariables, options?: C): Promise<{data: PieceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PieceConnectionQueryVariables, query: string}> {
        return requester<{data: PieceConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PieceConnectionQueryVariables, query: string}, PieceConnectionQueryVariables>(PieceConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  